import React, { useEffect, useState } from "react";
import api from "../../api/axios";
import Swal from "sweetalert2";
import "sweetalert2/dist/sweetalert2.min.css";

const CreatePurchase = ({ onSaved }) => {
  const [products, setProducts] = useState([]);
  const [suppliers, setSuppliers] = useState([]);
  const [purchaseItems, setPurchaseItems] = useState([]);
  const [selectedSupplier, setSelectedSupplier] = useState(null);
  const [billNo, setBillNo] = useState("");
  const [date, setDate] = useState("");
  const [loading, setLoading] = useState(false);

  // Bill No management
  const [supplierBills, setSupplierBills] = useState([]);
  const [billMode, setBillMode] = useState("auto"); // "auto", "existing", "manual"
  const [autoGeneratedBillNo, setAutoGeneratedBillNo] = useState("");

  // Modal toggles
  const [showAddSupplier, setShowAddSupplier] = useState(false);
  const [showAddProduct, setShowAddProduct] = useState(false);

  // New supplier form
  const [newSupplier, setNewSupplier] = useState({
    name: "",
    email: "",
    contact: "",
    address: "",
  });

  // New product form
  const [newProduct, setNewProduct] = useState({
    name: "",
    description: "",
    price: "",
    stock: "",
  });

  // ✅ Fetch suppliers and products on mount
  useEffect(() => {
    const fetchData = async () => {
      try {
        const [prodRes, suppRes] = await Promise.all([
          api.get("/products"),
          api.get("/suppliers"),
        ]);

        setProducts(prodRes.data.data || []);
        setSuppliers(suppRes.data.data || []);
      } catch (err) {
        Swal.fire("Error", "Failed to load data", "error");
      }
    };
    fetchData();
  }, []);

  // ✅ Fetch supplier bills and generate bill number when supplier is selected
  useEffect(() => {
    const fetchSupplierData = async () => {
      if (!selectedSupplier) {
        setBillNo("");
        setSupplierBills([]);
        setAutoGeneratedBillNo("");
        setBillMode("auto");
        return;
      }

      try {
        // Fetch existing bills for this supplier
        const [billsRes, nextBillRes] = await Promise.all([
          api.get(`/purchases/supplier-bills/${selectedSupplier._id}`),
          api.get(`/purchases/next-bill-no?supplier=${selectedSupplier._id}`)
        ]);

        const bills = billsRes.data.bills || [];
        const nextBill = nextBillRes.data.billNo || "";

        setSupplierBills(bills);
        setAutoGeneratedBillNo(nextBill);

        // Default to auto mode with generated bill number
        setBillMode("auto");
        setBillNo(nextBill);

      } catch (err) {
        console.error("Failed to fetch supplier data:", err);
        Swal.fire("Error", "Failed to load supplier data", "error");
      }
    };

    fetchSupplierData();
  }, [selectedSupplier]);

  // ✅ Handle bill mode change
  const handleBillModeChange = (mode) => {
    setBillMode(mode);
    
    if (mode === "auto") {
      setBillNo(autoGeneratedBillNo);
    } else if (mode === "existing" || mode === "manual") {
      setBillNo("");
    }
  };

  // ✅ Add product to purchase
  const handleAddItem = (productId) => {
    const product = products.find((p) => p._id === productId);
    if (!product) return;

    if (purchaseItems.some((i) => i.productId === productId)) {
      Swal.fire("Warning", "Product already added!", "warning");
      return;
    }

    setPurchaseItems([
      ...purchaseItems,
      { productId, name: product.name, quantity: 1, price: product.price },
    ]);
  };

  // ✅ Update quantity or price
  const handleChangeItem = (index, field, value) => {
    const updated = [...purchaseItems];
    updated[index][field] = value;
    setPurchaseItems(updated);
  };

  // ✅ Remove item
  const handleRemoveItem = (index) => {
    setPurchaseItems(purchaseItems.filter((_, i) => i !== index));
  };

  // ✅ Save purchase
  const handleSave = async () => {
    if (!selectedSupplier || !billNo || !date || purchaseItems.length === 0) {
      return Swal.fire("Error", "Please fill all fields and add at least one product", "error");
    }

    try {
      setLoading(true);

      const payload = {
        supplier: selectedSupplier._id,
        supplierName: selectedSupplier.name,
        billNo,
        date,
        items: purchaseItems,
      };

      await api.post("/purchases", payload);
      Swal.fire("Success", "Purchase saved successfully", "success");

      // Reset form
      setPurchaseItems([]);
      setSelectedSupplier(null);
      setDate("");
      setBillNo("");
      setSupplierBills([]);
      setAutoGeneratedBillNo("");
      setBillMode("auto");
      
      if (onSaved) onSaved();
    } catch (err) {
      Swal.fire("Error", err.response?.data?.message || "Failed to save purchase", "error");
    } finally {
      setLoading(false);
    }
  };

  // ✅ Add new supplier
  const handleAddSupplier = async () => {
    if (!newSupplier.name || !newSupplier.contact) {
      return Swal.fire("Error", "Name and contact are required", "error");
    }

    try {
      const res = await api.post("/suppliers", newSupplier);
      Swal.fire("Success", "Supplier added successfully", "success");
      setSuppliers((prev) => [...prev, res.data.data]);
      setShowAddSupplier(false);
      setNewSupplier({ name: "", email: "", contact: "", address: "" });
    } catch (err) {
      Swal.fire("Error", err.response?.data?.message || "Failed to add supplier", "error");
    }
  };

  // ✅ Add new product
  const handleAddProduct = async () => {
    if (!newProduct.name || !newProduct.price) {
      return Swal.fire("Error", "Name and price are required", "error");
    }

    try {
      const res = await api.post("/products", newProduct);
      Swal.fire("Success", "Product added successfully", "success");
      setProducts((prev) => [...prev, res.data.data]);
      setShowAddProduct(false);
      setNewProduct({ name: "", description: "", price: "", stock: "" });
    } catch (err) {
      Swal.fire("Error", err.response?.data?.message || "Failed to add product", "error");
    }
  };

  return (
    <div className="card shadow p-4">
      <h4 className="mb-4">🧾 Create Purchase</h4>

      {/* Supplier Selection */}
      <div className="d-flex align-items-center mb-3">
        <select
          className="form-select me-2"
          value={selectedSupplier?._id || ""}
          onChange={(e) => {
            const supplier = suppliers.find((s) => s._id === e.target.value);
            setSelectedSupplier(supplier || null);
          }}
        >
          <option value="">Select Supplier</option>
          {suppliers.map((s) => (
            <option key={s._id} value={s._id}>
              {s.name}
            </option>
          ))}
        </select>
        <button
          className="btn btn-outline-primary"
          onClick={() => setShowAddSupplier(true)}
        >
          + Add Supplier
        </button>
      </div>

      {/* Bill No Management */}
      {selectedSupplier && (
        <div className="card mb-3 p-3 bg-light">
          <label className="form-label fw-bold">Bill Number</label>
          
          {/* Bill Mode Options */}
          <div className="btn-group mb-3" role="group">
            <input
              type="radio"
              className="btn-check"
              name="billMode"
              id="billModeAuto"
              checked={billMode === "auto"}
              onChange={() => handleBillModeChange("auto")}
            />
            <label className="btn btn-outline-primary" htmlFor="billModeAuto">
              <i className="bi bi-lightning-fill me-1"></i>
              Auto Generate ({autoGeneratedBillNo})
            </label>

            {supplierBills.length > 0 && (
              <>
                <input
                  type="radio"
                  className="btn-check"
                  name="billMode"
                  id="billModeExisting"
                  checked={billMode === "existing"}
                  onChange={() => handleBillModeChange("existing")}
                />
                <label className="btn btn-outline-primary" htmlFor="billModeExisting">
                  <i className="bi bi-list-ul me-1"></i>
                  Select Existing
                </label>
              </>
            )}

            <input
              type="radio"
              className="btn-check"
              name="billMode"
              id="billModeManual"
              checked={billMode === "manual"}
              onChange={() => handleBillModeChange("manual")}
            />
            <label className="btn btn-outline-primary" htmlFor="billModeManual">
              <i className="bi bi-pencil-fill me-1"></i>
              Enter Manually
            </label>
          </div>

          {/* Bill No Input based on mode */}
          {billMode === "auto" && (
            <div className="input-group">
              <span className="input-group-text bg-success text-white">
                <i className="bi bi-check-circle-fill"></i>
              </span>
              <input
                type="text"
                className="form-control"
                value={billNo}
                readOnly
                placeholder="Auto-generated bill number"
              />
            </div>
          )}

          {billMode === "existing" && supplierBills.length > 0 && (
            <select
              className="form-select"
              value={billNo}
              onChange={(e) => setBillNo(e.target.value)}
            >
              <option value="">Select existing bill number</option>
              {supplierBills.map((bill, idx) => (
                <option key={idx} value={bill.billNo}>
                  {bill.billNo} - {new Date(bill.date).toLocaleDateString()}
                </option>
              ))}
            </select>
          )}

          {billMode === "manual" && (
            <input
              type="text"
              className="form-control"
              placeholder="Enter bill number manually"
              value={billNo}
              onChange={(e) => setBillNo(e.target.value)}
            />
          )}

          {/* Info Message */}
          <small className="text-muted mt-2">
            {supplierBills.length === 0 ? (
              <><i className="bi bi-info-circle me-1"></i>First purchase for this supplier. Bill format: {autoGeneratedBillNo}</>
            ) : (
              <><i className="bi bi-info-circle me-1"></i>This supplier has {supplierBills.length} previous purchase(s).</>
            )}
          </small>
        </div>
      )}

      {/* Product Selection */}
      <div className="d-flex align-items-center mb-3">
        <select
          className="form-select me-2"
          onChange={(e) => {
            handleAddItem(e.target.value);
            e.target.value = "";
          }}
          value=""
        >
          <option value="">Select Product</option>
          {products.map((p) => (
            <option key={p._id} value={p._id}>
              {p.name}
            </option>
          ))}
        </select>
        <button
          className="btn btn-outline-success"
          onClick={() => setShowAddProduct(true)}
        >
          + Add Product
        </button>
      </div>

      {/* Date */}
      <div className="row mb-3">
        <div className="col-md-4">
          <label>Date</label>
          <input
            type="date"
            className="form-control"
            value={date}
            onChange={(e) => setDate(e.target.value)}
          />
        </div>
      </div>

      {/* Purchase Items */}
      <table className="table table-bordered align-middle">
        <thead className="table-light">
          <tr>
            <th>Product</th>
            <th width="120">Qty</th>
            <th width="120">Price</th>
            <th width="150">Total</th>
            <th width="80"></th>
          </tr>
        </thead>
        <tbody>
          {purchaseItems.length > 0 ? (
            purchaseItems.map((item, i) => (
              <tr key={i}>
                <td>{item.name}</td>
                <td>
                  <input
                    type="number"
                    min="1"
                    className="form-control"
                    value={item.quantity}
                    onChange={(e) =>
                      handleChangeItem(i, "quantity", e.target.value)
                    }
                  />
                </td>
                <td>
                  <input
                    type="number"
                    min="0"
                    step="0.01"
                    className="form-control"
                    value={item.price}
                    onChange={(e) =>
                      handleChangeItem(i, "price", e.target.value)
                    }
                  />
                </td>
                <td>₹{(item.quantity * item.price).toFixed(2)}</td>
                <td>
                  <button
                    className="btn btn-danger btn-sm"
                    onClick={() => handleRemoveItem(i)}
                  >
                    X
                  </button>
                </td>
              </tr>
            ))
          ) : (
            <tr>
              <td colSpan="5" className="text-center text-muted">
                No items added.
              </td>
            </tr>
          )}
        </tbody>
        {purchaseItems.length > 0 && (
          <tfoot>
            <tr>
              <td colSpan="3" className="text-end fw-bold">Total Amount:</td>
              <td className="fw-bold">
                ₹{purchaseItems.reduce((sum, item) => sum + (item.quantity * item.price), 0).toFixed(2)}
              </td>
              <td></td>
            </tr>
          </tfoot>
        )}
      </table>

      {/* Save Button */}
      <button
        className="btn btn-primary mt-3"
        disabled={loading}
        onClick={handleSave}
      >
        {loading ? "Saving..." : "💾 Save Purchase"}
      </button>

      {/* ---------------- MODALS ---------------- */}

      {/* Add Supplier Modal */}
      {showAddSupplier && (
        <div
          className="modal d-block"
          tabIndex="-1"
          style={{ background: "#00000080" }}
        >
          <div className="modal-dialog">
            <div className="modal-content">
              <div className="modal-header">
                <h5>Add New Supplier</h5>
                <button
                  className="btn-close"
                  onClick={() => setShowAddSupplier(false)}
                ></button>
              </div>
              <div className="modal-body">
                <input
                  className="form-control mb-2"
                  placeholder="Name *"
                  value={newSupplier.name}
                  onChange={(e) =>
                    setNewSupplier({ ...newSupplier, name: e.target.value })
                  }
                />
                <input
                  className="form-control mb-2"
                  placeholder="Email"
                  value={newSupplier.email}
                  onChange={(e) =>
                    setNewSupplier({ ...newSupplier, email: e.target.value })
                  }
                />
                <input
                  className="form-control mb-2"
                  placeholder="Contact *"
                  value={newSupplier.contact}
                  onChange={(e) =>
                    setNewSupplier({ ...newSupplier, contact: e.target.value })
                  }
                />
                <input
                  className="form-control mb-2"
                  placeholder="Address"
                  value={newSupplier.address}
                  onChange={(e) =>
                    setNewSupplier({ ...newSupplier, address: e.target.value })
                  }
                />
              </div>
              <div className="modal-footer">
                <button
                  className="btn btn-secondary"
                  onClick={() => setShowAddSupplier(false)}
                >
                  Cancel
                </button>
                <button className="btn btn-primary" onClick={handleAddSupplier}>
                  Save
                </button>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Add Product Modal */}
      {showAddProduct && (
        <div
          className="modal d-block"
          tabIndex="-1"
          style={{ background: "#00000080" }}
        >
          <div className="modal-dialog">
            <div className="modal-content">
              <div className="modal-header">
                <h5>Add New Product</h5>
                <button
                  className="btn-close"
                  onClick={() => setShowAddProduct(false)}
                ></button>
              </div>
              <div className="modal-body">
                <input
                  className="form-control mb-2"
                  placeholder="Product Name *"
                  value={newProduct.name}
                  onChange={(e) =>
                    setNewProduct({ ...newProduct, name: e.target.value })
                  }
                />
                <input
                  className="form-control mb-2"
                  placeholder="Description"
                  value={newProduct.description}
                  onChange={(e) =>
                    setNewProduct({
                      ...newProduct,
                      description: e.target.value,
                    })
                  }
                />
                <input
                  className="form-control mb-2"
                  type="number"
                  step="0.01"
                  placeholder="Price *"
                  value={newProduct.price}
                  onChange={(e) =>
                    setNewProduct({ ...newProduct, price: e.target.value })
                  }
                />
                <input
                  className="form-control mb-2"
                  type="number"
                  placeholder="Initial Stock"
                  value={newProduct.stock}
                  onChange={(e) =>
                    setNewProduct({ ...newProduct, stock: e.target.value })
                  }
                />
              </div>
              <div className="modal-footer">
                <button
                  className="btn btn-secondary"
                  onClick={() => setShowAddProduct(false)}
                >
                  Cancel
                </button>
                <button className="btn btn-success" onClick={handleAddProduct}>
                  Save
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default CreatePurchase;